# Generated by Django 4.1.1 on 2022-10-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_message_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='message12',
        ),
    ]
