# Generated by Django 4.1.1 on 2022-10-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_rename_message_message12'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment7',
        ),
    ]
